// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehiculosAPI.Data;

#nullable disable

namespace VehiculosAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260422204922_AddMantenimientoYFallas")]
    partial class AddMantenimientoYFallas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehiculosAPI.Entities.Catalogos.CatEstatusFalla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CatEstatusFallas");
                });

            modelBuilder.Entity("VehiculosAPI.Entities.Catalogos.CatMarca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CatMarcas");
                });

            modelBuilder.Entity("VehiculosAPI.Entities.Catalogos.CatServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CatServicios");
                });

            modelBuilder.Entity("VehiculosAPI.Entities.Falla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CatEstatusFallaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsCritica")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CatEstatusFallaId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Fallas");
                });

            modelBuilder.Entity("VehiculosAPI.Entities.Mantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CatServicioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaServicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("KilometrajeActual")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CatServicioId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("VehiculosAPI.Entities.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("VehiculosAPI.Entities.Falla", b =>
                {
                    b.HasOne("VehiculosAPI.Entities.Catalogos.CatEstatusFalla", "CatEstatusFalla")
                        .WithMany()
                        .HasForeignKey("CatEstatusFallaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehiculosAPI.Entities.Vehiculo", "Vehiculo")
                        .WithMany("Fallas")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatEstatusFalla");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("VehiculosAPI.Entities.Mantenimiento", b =>
                {
                    b.HasOne("VehiculosAPI.Entities.Catalogos.CatServicio", "CatServicio")
                        .WithMany()
                        .HasForeignKey("CatServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehiculosAPI.Entities.Vehiculo", "Vehiculo")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatServicio");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("VehiculosAPI.Entities.Vehiculo", b =>
                {
                    b.HasOne("VehiculosAPI.Entities.Catalogos.CatMarca", "Marca")
                        .WithMany("Vehiculos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("VehiculosAPI.Entities.Catalogos.CatMarca", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("VehiculosAPI.Entities.Vehiculo", b =>
                {
                    b.Navigation("Fallas");

                    b.Navigation("Mantenimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
